#!/usr/bin/env ruby
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# frozen_string_literal: true

require 'optparse'
require_relative './libvirt/run'

opt = {}

options = OptionParser.new do |opts|
  opts.banner = 'Usage: multi-docker -n -c -q'

  opts.separator ''
  opts.on('-n HOSTNAME_PREFIX', '--name HOSTNAME_PREFIX', 'format: $tbox_group.$HOSTNAME') do |name|
    opt['hostname_prefix'] = name
  end

  opts.on('-c count', '--count count', 'how many libvirt-client do you need') do |num|
    opt['nr_vt'] = num
  end

  opts.on('-q queues', '--queues queues', 'separated by ","') do |queues|
    opt['queues'] = queues
  end

  opts.on_tail('-h', '--help', 'show this message') do
    puts opts
    exit
  end
end

if ARGV.size.zero?
  puts options
  exit 1
end

options.parse!(ARGV)

hostname = opt['hostname_prefix'] || "dc-1g.#{ENV['HOSTNAME']}"
nr_vt = opt['nr_vt'] || 1
queues = opt['queues'] || "dc-1g.#{ENV['HOSTNAME']}"

pids = multi_libvirt(hostname, nr_vt, queues)
save_pid pids
